### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by ataiwo473** [ghiobi/get-id-verified#14]
is it possible to add disable feature for returning customer and Ability to verified if the information is correct?

**Comment by ghiobi** [comment]
Could you please elaborate on the disable feature? I believe you mean, mark the user as verified for existing users, which has been integrated. The ability to verify if the user is already correct is already done. Simply click on `Verify User` scroll down to a checkbox and click verified. I'll add more elaborate docs later. Let me know if this the solution you're looking for, if not then

**Comment by ghiobi** [comment]
Closing cuz no replying.
